version: "2.3"
services:
  frontend:
    image: parsertongue/odin-tutorial:latest
    build:
      context: .
      dockerfile: Dockerfile
      # labels:
      #   org.parsertongue.description: "Frontend for Odin UI"
    depends_on:
      - backend
    restart: always
    ports:
      - "8880:7777"
    env_file:
      - ./.env
    environment:
      ODIN_API_BASE_URL: http://backend:9000/api
    volumes:
      - ./:/app:rw

  backend:
    image: parsertongue/odin-rest-api:latest
    restart: always
    ports:
      - "8881:9000"
    env_file:
      - ./.env
    healthcheck:
      # ensure backend is ready
      test: ["CMD", "curl", "localhost:9000/api"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 10