version: "3.8"
services:
  frontend:
    image: parsertongue/odin-tutorial:local
    container_name: odin-tutorial-challenges
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - backend
    restart: on-failure
    ports:
      - "8880:7777"
    env_file:
      - ./.env
    environment:
      ODIN_API_BASE_URL: http://localhost:9000/api
  backend:
    platform: linux/amd64
    image: parsertongue/odin-rest-api:latest
    container_name: odin-tutorial-rest-api
    restart: on-failure
    ports:
      - "8881:9000"
    env_file:
      - ./.env
    healthcheck:
      # ensure backend is ready
      test: ["CMD", "curl", "--fail", "127.0.0.1:9000/api/annotate?text=hello", "||", "exit", "1"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 10
